language: python
python:
  - "3.7"

before_install:
  - pip install pycodestyle

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - python -m pytest tests/ --disable-warnings
  - coverage run --source="src/" -m pytest --disable-warnings
  - pycodestyle src/ --ignore=E722,E501,E402